//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Facility.ServerModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class i_facilityEntities1 : DbContext
    {
        public i_facilityEntities1()
            : base("name=i_facilityEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alarm_history_master> alarm_history_master { get; set; }
        public virtual DbSet<frommail> frommails { get; set; }
        public virtual DbSet<handle_no_ping> handle_no_ping { get; set; }
        public virtual DbSet<hist_alarm_history_master> hist_alarm_history_master { get; set; }
        public virtual DbSet<hist_message_history_master> hist_message_history_master { get; set; }
        public virtual DbSet<hist_parameters_master> hist_parameters_master { get; set; }
        public virtual DbSet<jobcard_details> jobcard_details { get; set; }
        public virtual DbSet<mailmaster> mailmasters { get; set; }
        public virtual DbSet<message_code_master> message_code_master { get; set; }
        public virtual DbSet<message_history_master> message_history_master { get; set; }
        public virtual DbSet<monthdata> monthdatas { get; set; }
        public virtual DbSet<operationlog> operationlogs { get; set; }
        public virtual DbSet<parameter> parameters { get; set; }
        public virtual DbSet<pcb_details> pcb_details { get; set; }
        public virtual DbSet<pcb_parameters> pcb_parameters { get; set; }
        public virtual DbSet<pcbdaq> pcbdaqs { get; set; }
        public virtual DbSet<pcbdaqin_tbl> pcbdaqin_tbl { get; set; }
        public virtual DbSet<pcbdps_master> pcbdps_master { get; set; }
        public virtual DbSet<program_master> program_master { get; set; }
        public virtual DbSet<sharathtable> sharathtables { get; set; }
        public virtual DbSet<shift_master> shift_master { get; set; }
        public virtual DbSet<smtpdetail> smtpdetails { get; set; }
        public virtual DbSet<tbl_autoreport_log> tbl_autoreport_log { get; set; }
        public virtual DbSet<tbl_autoreportbasedon> tbl_autoreportbasedon { get; set; }
        public virtual DbSet<tbl_autoreportsetting> tbl_autoreportsetting { get; set; }
        public virtual DbSet<tbl_autoreporttime> tbl_autoreporttime { get; set; }
        public virtual DbSet<tbl_axisdet> tbl_axisdet { get; set; }
        public virtual DbSet<tbl_axisdetails1> tbl_axisdetails1 { get; set; }
        public virtual DbSet<tbl_axisdetails2> tbl_axisdetails2 { get; set; }
        public virtual DbSet<tbl_deletedprogdet> tbl_deletedprogdet { get; set; }
        public virtual DbSet<tbl_genericfilepath> tbl_genericfilepath { get; set; }
        public virtual DbSet<tbl_machinestatusrealtime> tbl_machinestatusrealtime { get; set; }
        public virtual DbSet<tbl_prodorderlosses> tbl_prodorderlosses { get; set; }
        public virtual DbSet<tbl_reportmaster> tbl_reportmaster { get; set; }
        public virtual DbSet<tbl_savencprogver> tbl_savencprogver { get; set; }
        public virtual DbSet<tbl_servodetails> tbl_servodetails { get; set; }
        public virtual DbSet<tbl_utilreport> tbl_utilreport { get; set; }
        public virtual DbSet<tblactivitylog> tblactivitylogs { get; set; }
        public virtual DbSet<tblandondispdet> tblandondispdets { get; set; }
        public virtual DbSet<tblandonimagetextscheduleddisplay> tblandonimagetextscheduleddisplays { get; set; }
        public virtual DbSet<tblapp_paths> tblapp_paths { get; set; }
        public virtual DbSet<tblatccounter> tblatccounters { get; set; }
        public virtual DbSet<tblbreakdown> tblbreakdowns { get; set; }
        public virtual DbSet<tblcustomer> tblcustomers { get; set; }
        public virtual DbSet<tbldailyprodstatu> tbldailyprodstatus { get; set; }
        public virtual DbSet<tbldaytiming> tbldaytimings { get; set; }
        public virtual DbSet<tbldowntimecategory> tbldowntimecategories { get; set; }
        public virtual DbSet<tbldowntimedetail> tbldowntimedetails { get; set; }
        public virtual DbSet<tblemailescalation> tblemailescalations { get; set; }
        public virtual DbSet<tblendcode> tblendcodes { get; set; }
        public virtual DbSet<tblescalationlog> tblescalationlogs { get; set; }
        public virtual DbSet<tblgenericworkcode> tblgenericworkcodes { get; set; }
        public virtual DbSet<tblgenericworkentry> tblgenericworkentries { get; set; }
        public virtual DbSet<tblhistaxisdet> tblhistaxisdets { get; set; }
        public virtual DbSet<tblhistaxisdetails1> tblhistaxisdetails1 { get; set; }
        public virtual DbSet<tblhistaxisdetails2> tblhistaxisdetails2 { get; set; }
        public virtual DbSet<tblhistbreakdown> tblhistbreakdowns { get; set; }
        public virtual DbSet<tblhistdailyprodstatu> tblhistdailyprodstatus { get; set; }
        public virtual DbSet<tblhistlossescode> tblhistlossescodes { get; set; }
        public virtual DbSet<tblhistlossofentry> tblhistlossofentries { get; set; }
        public virtual DbSet<tblhistmimic> tblhistmimics { get; set; }
        public virtual DbSet<tblhistprodandondisp> tblhistprodandondisps { get; set; }
        public virtual DbSet<tblhistservodetail> tblhistservodetails { get; set; }
        public virtual DbSet<tblhistutilreport> tblhistutilreports { get; set; }
        public virtual DbSet<tblhistworkorderentry> tblhistworkorderentries { get; set; }
        public virtual DbSet<tblholdcode> tblholdcodes { get; set; }
        public virtual DbSet<tblholidaymanagment> tblholidaymanagments { get; set; }
        public virtual DbSet<tblholiday> tblholidays { get; set; }
        public virtual DbSet<tblholidaytypemaster> tblholidaytypemasters { get; set; }
        public virtual DbSet<tbllossescodes2018> tbllossescodes2018 { get; set; }
        public virtual DbSet<tblmachineaxisdetail> tblmachineaxisdetails { get; set; }
        public virtual DbSet<tblmachinecategory> tblmachinecategories { get; set; }
        public virtual DbSet<tblmailid> tblmailids { get; set; }
        public virtual DbSet<tblmasterparts_st_sw> tblmasterparts_st_sw { get; set; }
        public virtual DbSet<tblmode> tblmodes { get; set; }
        public virtual DbSet<tblmode2018> tblmode2018 { get; set; }
        public virtual DbSet<tblmodulehelper> tblmodulehelpers { get; set; }
        public virtual DbSet<tblmodulemaster> tblmodulemasters { get; set; }
        public virtual DbSet<tblmodule> tblmodules { get; set; }
        public virtual DbSet<tblmultipleworkorder> tblmultipleworkorders { get; set; }
        public virtual DbSet<tblncprogramtransfermain> tblncprogramtransfermains { get; set; }
        public virtual DbSet<tbloeedashboardfinalvariable> tbloeedashboardfinalvariables { get; set; }
        public virtual DbSet<tbloeedashboardvariable> tbloeedashboardvariables { get; set; }
        public virtual DbSet<tbloeedashboardvariablestoday> tbloeedashboardvariablestodays { get; set; }
        public virtual DbSet<tbloperatordashboard> tbloperatordashboards { get; set; }
        public virtual DbSet<tbloperatorheader> tbloperatorheaders { get; set; }
        public virtual DbSet<tblplannedbreak> tblplannedbreaks { get; set; }
        public virtual DbSet<tblplant> tblplants { get; set; }
        public virtual DbSet<tblpresenttool> tblpresenttools { get; set; }
        public virtual DbSet<tblpriorityalarm> tblpriorityalarms { get; set; }
        public virtual DbSet<tblprodplanmaster> tblprodplanmasters { get; set; }
        public virtual DbSet<tblprogramtransferhistory> tblprogramtransferhistories { get; set; }
        public virtual DbSet<tblreportholder> tblreportholders { get; set; }
        public virtual DbSet<tblrolemodulelink> tblrolemodulelinks { get; set; }
        public virtual DbSet<tblrole> tblroles { get; set; }
        public virtual DbSet<tblsapinput> tblsapinputs { get; set; }
        public virtual DbSet<tblsendermailid> tblsendermailids { get; set; }
        public virtual DbSet<tblsetupmaint> tblsetupmaints { get; set; }
        public virtual DbSet<tblshift_breaks> tblshift_breaks { get; set; }
        public virtual DbSet<tblshift_mstr> tblshift_mstr { get; set; }
        public virtual DbSet<tblshiftdetail> tblshiftdetails { get; set; }
        public virtual DbSet<tblshiftdetails_machinewise> tblshiftdetails_machinewise { get; set; }
        public virtual DbSet<tblshiftmethod> tblshiftmethods { get; set; }
        public virtual DbSet<tblshiftplanner> tblshiftplanners { get; set; }
        public virtual DbSet<tblshop> tblshops { get; set; }
        public virtual DbSet<tblstdtoollife> tblstdtoollives { get; set; }
        public virtual DbSet<tbltoolcounter> tbltoolcounters { get; set; }
        public virtual DbSet<tbltosapfilepath> tbltosapfilepaths { get; set; }
        public virtual DbSet<tbltosapshopname> tbltosapshopnames { get; set; }
        public virtual DbSet<tblunit> tblunits { get; set; }
        public virtual DbSet<tblwolossess> tblwolossesses { get; set; }
        public virtual DbSet<tblworeport> tblworeports { get; set; }
        public virtual DbSet<tblandondisplayrotate> tblandondisplayrotates { get; set; }
        public virtual DbSet<tblprimitivemaintainancescheduling> tblprimitivemaintainanceschedulings { get; set; }
        public virtual DbSet<tblpartmodule> tblpartmodules { get; set; }
        public virtual DbSet<weekdata> weekdatas { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
        public virtual DbSet<tblmachinesensor> tblmachinesensors { get; set; }
        public virtual DbSet<tblsensordatalink> tblsensordatalinks { get; set; }
        public virtual DbSet<tblsensorgroup> tblsensorgroups { get; set; }
        public virtual DbSet<tblsensormaster> tblsensormasters { get; set; }
        public virtual DbSet<tbloperatorentry> tbloperatorentries { get; set; }
        public virtual DbSet<tblpmchecklist> tblpmchecklists { get; set; }
        public virtual DbSet<tblpmcheckpoint> tblpmcheckpoints { get; set; }
        public virtual DbSet<tblmachinedetail> tblmachinedetails { get; set; }
        public virtual DbSet<tblrejectqty> tblrejectqties { get; set; }
        public virtual DbSet<tblrejectreason> tblrejectreasons { get; set; }
        public virtual DbSet<tbl_prodandondisp> tbl_prodandondisp { get; set; }
        public virtual DbSet<tbl_prodmanmachine> tbl_prodmanmachine { get; set; }
        public virtual DbSet<tblpartlearningreport> tblpartlearningreports { get; set; }
        public virtual DbSet<tbltoollifeoperator> tbltoollifeoperators { get; set; }
        public virtual DbSet<parameters_master> parameters_master { get; set; }
        public virtual DbSet<tbllivemode> tbllivemodes { get; set; }
        public virtual DbSet<tblmimic> tblmimics { get; set; }
        public virtual DbSet<tblpartscountandcutting> tblpartscountandcuttings { get; set; }
        public virtual DbSet<tbllossescode> tbllossescodes { get; set; }
        public virtual DbSet<tbloeedetail> tbloeedetails { get; set; }
        public virtual DbSet<tblpart> tblparts { get; set; }
        public virtual DbSet<tblbottelneck> tblbottelnecks { get; set; }
        public virtual DbSet<tblworkorderentry> tblworkorderentries { get; set; }
        public virtual DbSet<tblcellpart> tblcellparts { get; set; }
        public virtual DbSet<tbl_cbmparameters> tbl_cbmparameters { get; set; }
        public virtual DbSet<dashboard_menus> dashboard_menus { get; set; }
        public virtual DbSet<sidebar_menus> sidebar_menus { get; set; }
        public virtual DbSet<tblcell> tblcells { get; set; }
        public virtual DbSet<tbllossofentry> tbllossofentries { get; set; }
    }
}
