//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Facility.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidebar_menus
    {
        public int id { get; set; }
        public string SubMenuName { get; set; }
        public string MenuName { get; set; }
        public string SubMenuURL { get; set; }
        public string MenuURL { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
