//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Facility.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhistprodandondisp
    {
        public int ProdDashboardID { get; set; }
        public int MachineID { get; set; }
        public System.DateTime CorrectedDate { get; set; }
        public int WOID { get; set; }
        public Nullable<decimal> UtilPercent { get; set; }
        public decimal TotalLoss { get; set; }
        public decimal TotalSetup { get; set; }
        public decimal TotalOperatingTime { get; set; }
        public System.DateTime InsertedOn { get; set; }
    
        public virtual tblhistworkorderentry tblhistworkorderentry { get; set; }
        public virtual tblmachinedetail tblmachinedetail { get; set; }
    }
}
