//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Facility.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbloeedetail
    {
        public int OeeId { get; set; }
        public int CellId { get; set; }
        public decimal OperatingTime { get; set; }
        public string CorrectedDate { get; set; }
        public decimal TotalTime { get; set; }
        public decimal LossTime { get; set; }
        public decimal Availability { get; set; }
        public decimal performance { get; set; }
        public decimal Quality { get; set; }
        public decimal OEEPercent { get; set; }
        public decimal BDTime { get; set; }
        public decimal scrapqty { get; set; }
        public int TotalQuantity { get; set; }
        public decimal PerformanceFactor { get; set; }
        public decimal TotalProduction { get; set; }
        public Nullable<decimal> AvailabilityInMin { get; set; }
        public int MachineId { get; set; }
        public decimal PowerOffTime { get; set; }
        public decimal MinorLossTime { get; set; }
        public decimal OPwithMinorStoppage { get; set; }
        public decimal PlannedBrkDurationinMin { get; set; }
        public decimal PlannedCycleTimeInMin { get; set; }
        public int LastmachineYieldQty { get; set; }
        public decimal BottleNeckMachineYieldQtry { get; set; }
        public decimal LoadingUnLoadingWithProd { get; set; }
    
        public virtual tblcell tblcell { get; set; }
    }
}
