//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Facility.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbloperatorentry
    {
        public int OpeID { get; set; }
        public string OPID { get; set; }
        public int ProducationOrderNo { get; set; }
        public string OperationNo { get; set; }
        public string PartNo { get; set; }
        public int ProductionOrderQty { get; set; }
        public int ProcessQty { get; set; }
        public string Shift { get; set; }
        public int YieldQty { get; set; }
        public int ScrapQty { get; set; }
        public int Total { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> CorrectedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> HoldCodeID { get; set; }
        public Nullable<System.DateTime> HoldTime { get; set; }
        public Nullable<int> IsHold { get; set; }
        public Nullable<int> HoldDuration { get; set; }
        public Nullable<int> IsPartialFinish { get; set; }
        public Nullable<int> IsFinish { get; set; }
        public Nullable<int> Status { get; set; }
        public int MachineID { get; set; }
    }
}
