//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Facility.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpartmodule
    {
        public int Pid { get; set; }
        public int CellID { get; set; }
        public int No_Of_Modules { get; set; }
        public int No_Of_Parts { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public string CellName { get; set; }
        public string CellDescription { get; set; }
        public int MachineID { get; set; }
    
        public virtual tblcell tblcell { get; set; }
    }
}
