//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Facility.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblworkorderentry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblworkorderentry()
        {
            this.tbl_prodandondisp = new HashSet<tbl_prodandondisp>();
            this.tbl_prodmanmachine = new HashSet<tbl_prodmanmachine>();
            this.tblrejectqties = new HashSet<tblrejectqty>();
        }
    
        public int HMIID { get; set; }
        public int MachineID { get; set; }
        public System.DateTime WOStart { get; set; }
        public Nullable<System.DateTime> WOEnd { get; set; }
        public string PartNo { get; set; }
        public int ShiftID { get; set; }
        public string OperatorID { get; set; }
        public string Prod_Order_No { get; set; }
        public string OperationNo { get; set; }
        public int Yield_Qty { get; set; }
        public int ScrapQty { get; set; }
        public int Total_Qty { get; set; }
        public int ProcessQty { get; set; }
        public int Status { get; set; }
        public string CorrectedDate { get; set; }
        public int IsStarted { get; set; }
        public int IsFinished { get; set; }
        public int IsPartialFinish { get; set; }
        public int isWorkOrder { get; set; }
        public System.DateTime PEStartTime { get; set; }
        public int IsMultiWO { get; set; }
        public int IsHold { get; set; }
        public int IsFlag { get; set; }
        public Nullable<int> ProdOrderQty { get; set; }
        public string FGCode { get; set; }
        public Nullable<int> HoldCodeID { get; set; }
        public Nullable<System.DateTime> HoldTime { get; set; }
        public Nullable<int> HoldDuration { get; set; }
        public Nullable<bool> isSplit { get; set; }
        public Nullable<int> WOMonth { get; set; }
        public Nullable<int> WOYear { get; set; }
        public Nullable<int> WOWeekNumber { get; set; }
        public Nullable<int> WOQuarter { get; set; }
        public int CellID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_prodandondisp> tbl_prodandondisp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_prodmanmachine> tbl_prodmanmachine { get; set; }
        public virtual tblmachinedetail tblmachinedetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblrejectqty> tblrejectqties { get; set; }
    }
}
